= Bajar PDFs del ministerio sobre el COVID

Este script está pensado para que, mediante un CRON, se tenga la Última actualización en forma de PDF.
Es muy simple, así que no detecta saltos ni pérdidas, simplemente checkea si existe en el momento de ejecución un informe con un número de sequencia superior en una unidad al que guarda en un fichero.dat.
En caso afirmativo, actualiza dicho fichero y baja el fichero. En caso de no encontrar la url con la sequencia incrementada, no hace nada.

== Cron

Para que se ejecute todos los días a las 17:30:

`30 17 * * *`

Entonces se mete con el comando:

`crontab -e`

`crontab -l`

Yo me lo dejo para que lo tire cada 8 horas:

`0 */8 * * * /home/javierito/.bin/scripts/covid-pdf-autodownload/download_daily_pdf.sh`

==  Ficheros pochos

Cuando se baja mal suele ocupar un tamaño fijo:

. Fichero pocho `find . -type f -size 19k -exec rm {} \;`
. Fichero mal bajado `find . -type f -size 0k -exec rm {} \;`
.. También creo que acepta `--empty` en vez del tamaño a 0

